namespace: ansible
name: emc
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:coll-test/ansible.emc.git
documentation: https://github.com/coll-test/ansible.emc/tree/master/docs
homepage: https://github.com/coll-test/ansible.emc
issues: https://github.com/coll-test/ansible.emc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
